/**
 * KAIROS — Audio & Ambient Sound Transcripts (Phase 8 Accessibility)
 * Provides text descriptions and transcripts for ambient tracks and audio cues
 * to ensure accessibility for deaf and hard-of-hearing users or users with muted audio.
 */

export const AUDIO_TRACK_TRANSCRIPTS: Record<string, string> = {
  "ordinary": "Low, domestic room frequency with faint ticking and gentle ambient drone.",
  "mountain": "Distant high-altitude mountain winds and sparse, hollow resonant chords.",
  "creation": "Deep sub-bass swell expanding into vast, crystalline harmonic frequencies.",
  "cain-abel": "Tense, rhythmic plucked acoustic strings with dry, dusty reverberation.",
  "silence": "Absolute acoustic stillness with faint sub-audible room breath.",
  "flood": "Rising deluge roar, deep rolling thunder, and heavy wooden timber creaks.",
  "babel": "Disorienting polyphonic vocal murmurs shifting across stereophonic channels.",
  "abraham": "Solitary wind across stony plains with slow, contemplative cello drone.",
  "jacob": "Straining low strings, rhythmic struggle cadence, and distant river murmur.",
  "joseph": "Cold cistern resonance, echo of falling dirt, and dry wind over the pit rim.",
  "moses": "Gentle Nile water lap against reeds giving way to low desert tension.",
  "burning-bush": "Intense crackling flame resonance that maintains steady warmth without destruction.",
  "plagues": "Ominous heavy drone with swarm fluttering and low brass pulses.",
  "red-sea": "Massive walls of suspended water roaring, strained sea-floor gravel underfoot.",
  "sinai": "Piercing ram's horn blast, violent rolling thunder, and seismic mountain tremor.",
  "wilderness": "Dry desert wind buffeting solitary travelers with sparse, weary guitar pulses.",
  "jericho": "Sevenfold trumpet blast, rising circular chanting, and tectonic stone collapse.",
  "judges": "Fragmented, cyclical tribal percussion and dissonant bowed strings.",
  "ruth": "Warm afternoon breeze rustling ripe barley fields with tender lute progression.",
  "samuel": "Whispered nighttime breath in temple silence; an unanswered calling voice.",
  "saul": "Uneasy palace reverberation, metallic armor rustle, and brooding cello tension.",
  "david-goliath": "Vast valley acoustic emptiness, distant armored clatter, and rising sling hum.",
  "david-jonathan": "Intimate two-instrument counterpoint, quiet weeping, and gentle stone stillness.",
  "david-saul": "Damp cavern acoustic echo, muffled breathing in darkness, and blade sliding past cloth.",
  "david-bathsheba": "Sultry, heavy nighttime air, distant palace flutes, and a sudden hollow chord.",
  "solomon": "Lush cedarwood acoustic reverb, ornate harp phrasing, and hollow gold resonance.",
  "the-temple": "Massive stone nave reverberation, billows of incense, and choral chanting.",
  "elijah": "Dry drought whisper, crackling altar flame, and sudden violent rainstorm roar.",
  "elisha": "Jordan river rapids, quiet prophetic mantle rustling, and deep stillness.",
  "divided-kingdom": "Two discordant keys playing simultaneously across left and right channels.",
  "isaiah": "Shaking temple foundations, smoke-filled air, and thundering seraphic antiphons.",
  "jeremiah": "Dull subterranean mud drops in a dry cistern, heavy solitary lamentation.",
  "fall-of-jerusalem": "Roaring city conflagration, breaking stone ramparts, and distant wailing.",
  "daniel": "Looming predatory breathing in an echoing stone den, followed by unnatural calm.",
  "esther": "Gilded Persian banquet murmurs, sharp wine goblets, and tense whispered counsel.",
  "job": "Desolate ash heap wind, tearing cloth, and an approaching cosmic whirlwind roar.",
  "return-exile": "Slow, weary caravan marching cadence, mingled tears of sorrow and celebration.",
  "ezra-nehemiah": "Trowels scraping stone mortar, watchman horn calls, and resolute work rhythm.",
  "the-long-silence": "Four hundred years of quiet night air, stars slowly wheeling over dormant hills.",
  "gospel": "Clear dawn atmosphere, solitary footsteps on limestone, and warm light.",
  "gethsemane": "Heavy midnight olive-grove dew, anguished gasping breath, and trembling stillness.",
  "arrest": "Jarring metal torches, rough boots in gravel, and abrupt urgent shouts.",
  "trial": "Echoing Roman praetorium stone floor, water splashing into a bronze washbasin.",
  "crucifixion-silence": "Stark noon twilight, absolute sonic emptiness, and ragged, laboured breathing.",
  "empty-tomb": "Chilled morning stone, displaced boulder grinding, and sudden rushing air.",
  "resurrection": "Warm golden resonance breaking through silence with boundless harmonic peace.",
  "acts-dawn": "Rushing mighty wind gust, dynamic flame resonance, and multilingual voices.",
  "expansion": "Open Mediterranean sea wind, horse hooves on Roman cobblestone roads.",
  "revelation-vast": "Sound of many waters, cosmic thunder, and an endless multitude singing.",
  "collapse-stack": "Deep sub-harmonic resonance compressing time into a singular focal point.",
};

export const AUDIO_AMBIENT_TRANSCRIPTS: Record<string, string> = {
  "subtle-room": "Soft interior room ambiance with subtle ventilation hum.",
  "mountain-wind": "Cold, sweeping high-elevation mountain gusts.",
  "space-resonance": "Expansive, frictionless deep-space harmonic drone.",
  "field-dusk": "Evening field breeze, distant night insects, and drying grasses.",
  "none": "Silence.",
  "deluge-thunder": "Violent rain beating down, deep seismic thunder claps.",
  "tower-wind-voices": "High-altitude scaffolding wind, shifting vocal murmurs.",
  "desert-night": "Chill night breeze shifting fine sand grains under open sky.",
  "river-night-insects": "Gentle Jordan river current and chirping nocturnal reeds.",
  "pit-wind": "Hollow cistern drafts swirling around dry subterranean stone.",
  "caravan-bells": "Rhythmic bronze camel bells clanking in desert heat.",
  "river-nile-water": "Warm slow-moving river water swirling around riverbank papyrus.",
  "desert-fire-hum": "Steady burning warmth hum without any spitting embers.",
  "nile-locusts-dread": "Deep drone layered with the distant hum of millions of wings.",
  "crowd-panic-water": "Surging sea waves towering overhead, hurried footsteps.",
  "sinai-trumpet-thunder": "Piercing shofar blast echoing between cloud-wrapped granite peaks.",
  "desert-exhaustion-wind": "Desolate desert gale carrying dust across barren wasteland.",
  "jericho-horns": "Long continuous horn blast rising in unison with a great shout.",
  "judges-strife": "Clashing metal, shouting in valleys, and unsteady rhythm.",
  "harvest-breeze": "Gentle midday wind rustling wheat stalks in sunny terraces.",
  "sanctuary-whisper": "Sacred sanctuary silence, flickering oil lamp wick, and soft breath.",
  "court-tension": "Stifled whispers, nervous pacing upon polished stone floors.",
  "valley-tension": "Wind blowing down the valley of Elah between two armed armies.",
  "friendship-quiet": "Quiet outdoor shelter, rustling bowstrings, and shared sorrow.",
  "cave-darkness": "Muffled cavern dripping water, deep shadow stillness.",
  "palace-night": "Warm palace balcony breeze, crickets in courtyard gardens.",
  "temple-smoke-incense": "Crackling altar coals and thick billows of frankincense.",
  "carmel-drought-whisper": "Crackling parched soil, sudden torrential cloudburst roar.",
  "river-jordan-peace": "Smooth river flow over rounded river stones.",
  "divided-distant-cries": "Distant fires and faint border disputes across hills.",
  "throne-room-seraphim": "Vibrating temple foundations, rushing wings, and singing.",
  "dungeon-mud-lament": "Damp subterranean dripping, slow labored sighing.",
  "jerusalem-ruins-smoke": "Rubble settling, crackling cedar beams in distant ruins.",
  "babylon-palace": "Ornate court musicians playing harps and pipes across grand plazas.",
  "susa-banquet": "Chinking goblets, silk curtains rustling, and quiet royal intrigue.",
  "ash-wind": "Dry ashes blowing across desolate mounds outside town walls.",
  "ruined-wall-wind": "Wind whistling through fractured stone ramparts.",
  "temple-foundation-tears": "Wailing elders mingling with joyful shouts of youths.",
  "expectant-silence": "Vast twilight silence under cold desert stars.",
  "crowd-dust": "Murmuring crowds moving along unpaved Galilean roads.",
  "galilee-shore": "Small lake waves lapping against fishing boat hulls.",
  "gethsemane-dusk": "Rustling olive leaves in a cold nocturnal garden breeze.",
  "torch-rattle": "Flaring pine pitch torches, bronze armor rattling.",
  "courtyard-fire": "Crackling courtyard charcoal fire, shivering onlookers.",
  "silent-agony": "Stark silence broken only by laboured breathing under darkness.",
  "garden-dawn": "Early birdsong at sunrise, fresh morning dew drops.",
  "expansion-wind": "Dynamic sea winds billowing sails across the open horizon.",
  "heaven-thunders": "Seven thunders rolling across crystal sea, golden harps.",
};

export function getAudioTranscript(trackId?: string, ambientId?: string): string {
  const parts: string[] = [];
  if (trackId && AUDIO_TRACK_TRANSCRIPTS[trackId]) {
    parts.push(`Score: ${AUDIO_TRACK_TRANSCRIPTS[trackId]}`);
  }
  if (ambientId && AUDIO_AMBIENT_TRANSCRIPTS[ambientId]) {
    parts.push(`Atmosphere: ${AUDIO_AMBIENT_TRANSCRIPTS[ambientId]}`);
  }
  return parts.length > 0 ? parts.join(" | ") : "Subtle atmospheric soundscape.";
}
