export interface ChronicleChapter {
  id: string;
  slug: string;
  title: string;
  nativeTitle?: string;
  scripture: string;
  summary: string;
  route: string;
  bookId?: string;
  bookName?: string;
  order: number;
  pov?: string;
  emotion?: string;
  keyWitnesses?: string[];
  testament: "old" | "new" | "prologue" | "epilogue";
}

export interface ChronicleArc {
  id: string;
  eraId: string;
  name: string;
  nativeName?: string;
  description: string;
  bookRange: string;
  color: string;
  chapters: ChronicleChapter[];
}

export interface ChronicleEra {
  id: string;
  name: string;
  tagline: string;
  timeframe: string;
  testament: "old" | "new" | "narrative";
  badgeColor: string;
  accentBorder: string;
  arcs: ChronicleArc[];
}

export const CANON_ERAS: ChronicleEra[] = [
  // 0. Prologue
  {
    id: "prologue",
    name: "The Ordinary & The Ridge",
    tagline: "Before the visions begin — the weight of fixing, broken communion, and the mountain slope.",
    timeframe: "Contemporary / Mount Makiling Ridge",
    testament: "narrative",
    badgeColor: "bg-amber-950/40 text-amber-300 border-amber-500/30",
    accentBorder: "border-amber-500/40",
    arcs: [
      {
        id: "arc-prologue",
        eraId: "prologue",
        name: "Prologue: Ordinary Life",
        nativeName: "Bago Umakyat ng Bundok",
        description: "Seventeen-year-old Theo battles the instinct to engineer and repair broken human relationships.",
        bookRange: "Modern Day Setting",
        color: "#c99a5e",
        chapters: [
          {
            id: "begin-ordinary",
            slug: "begin",
            title: "Ordinary Life · The Weight of Fixing",
            nativeTitle: "Ang Timbang ng Pagsasaayos",
            scripture: "Luke 10:41–42 · Matthew 11:28",
            summary: "Theo in his room with 14 open tabs, an overdue assignment, and a fracture with his best friend Sam.",
            route: "/begin",
            order: 1,
            pov: "Theo",
            emotion: "restless, burdened",
            testament: "prologue",
          },
          {
            id: "mountain-ridge",
            slug: "mountain",
            title: "The Mountain Slope · The High Limestone",
            nativeTitle: "Ang Mataas na Apog sa Paglubog ng Araw",
            scripture: "1 Kings 19:11–12",
            summary: "Dusk on the mountain ridge. Theo reads Genesis on his lap until physical exhaustion turns into dreaming vision.",
            route: "/experience/mountain",
            order: 2,
            pov: "Theo",
            emotion: "quiet, threshold",
            testament: "prologue",
          },
        ],
      },
    ],
  },

  // 1. Creation & Primeval History
  {
    id: "creation-primeval",
    name: "Creation & The Primeval World",
    tagline: "Cosmic order spoken from darkness, the fracture of Eden, and the first generations.",
    timeframe: "The Beginning of Days",
    testament: "old",
    badgeColor: "bg-emerald-950/40 text-emerald-300 border-emerald-500/30",
    accentBorder: "border-emerald-500/40",
    arcs: [
      {
        id: "arc-creation-eden",
        eraId: "creation-primeval",
        name: "Genesis: The Cosmic Beginning",
        nativeName: "Ang Paglikha at ang Unang Hukay",
        description: "From light divided over primordial waters to the first exile and the grave in the soil.",
        bookRange: "Genesis 1 – 11",
        color: "#34d399",
        chapters: [
          {
            id: "genesis-creation",
            slug: "creation",
            title: "The Divided Light",
            nativeTitle: "Ang Hinating Liwanag",
            scripture: "Genesis 1:1 – 2:3",
            summary: "The cosmos spoken into order from deep water and darkness. Scale beyond analysis.",
            route: "/experience/genesis/creation",
            bookId: "genesis",
            bookName: "Genesis",
            order: 3,
            pov: "Omniscient / Wonder",
            emotion: "reverence, awe",
            keyWitnesses: ["Adam", "Eve"],
            testament: "old",
          },
          {
            id: "genesis-eden",
            slug: "eden",
            title: "The Garden & The Breath",
            nativeTitle: "Ang Hininga sa Putik at ang Bungang Ipinagbawal",
            scripture: "Genesis 2:4 – 3:24",
            summary: "The intimacy of dust and breath, the whisper of distrust, and expulsion past the flaming sword.",
            route: "/experience/genesis/eden",
            bookId: "genesis",
            bookName: "Genesis",
            order: 4,
            pov: "Witness",
            emotion: "intimacy, rupture",
            keyWitnesses: ["Adam", "Eve"],
            testament: "old",
          },
          {
            id: "genesis-cain-abel",
            slug: "cain-and-abel",
            title: "Cain and Abel · The Furrows at Dusk",
            nativeTitle: "Ang Unang Libingan sa Bukid",
            scripture: "Genesis 4:1–16",
            summary: "Two altars, rising smoke, simmering resentment, and the first human blood crying from the ground.",
            route: "/experience/genesis/cain-and-abel",
            bookId: "genesis",
            bookName: "Genesis",
            order: 5,
            pov: "Theo / Immersive Witness",
            emotion: "dread, helplessness",
            keyWitnesses: ["Cain", "Abel"],
            testament: "old",
          },
          {
            id: "genesis-flood",
            slug: "flood",
            title: "The Deluge · Breaking of the Deeps",
            nativeTitle: "Ang Pagkawasak ng mga Balon ng Kalaliman",
            scripture: "Genesis 6:5 – 9:17",
            summary: "The heavy cedar timber ark in the torrential abyss. Total judgment followed by the quiet rainbow covenant.",
            route: "/experience/genesis/flood",
            bookId: "genesis",
            bookName: "Genesis",
            order: 6,
            pov: "Witness",
            emotion: "judgment, mercy",
            keyWitnesses: ["Noah"],
            testament: "old",
          },
          {
            id: "genesis-babel",
            slug: "babel",
            title: "The Tower of Babel",
            nativeTitle: "Ang Tore sa Kapatagan ng Sinar",
            scripture: "Genesis 11:1–9",
            summary: "Fired brick and bitumen reaching toward heaven. The scattering of languages and the shattering of self-deification.",
            route: "/experience/genesis/babel",
            bookId: "genesis",
            bookName: "Genesis",
            order: 7,
            pov: "Witness",
            emotion: "confusion, humility",
            testament: "old",
          },
        ],
      },
    ],
  },

  // 2. The Patriarchs
  {
    id: "patriarchs",
    name: "The Patriarchs & The Covenant",
    tagline: "A family summoned under stars, tested upon altars, and preserved through slavery.",
    timeframe: "c. 2000 – 1600 BC",
    testament: "old",
    badgeColor: "bg-sky-950/40 text-sky-300 border-sky-500/30",
    accentBorder: "border-sky-500/40",
    arcs: [
      {
        id: "arc-patriarchs",
        eraId: "patriarchs",
        name: "Genesis: The Covenant Line",
        nativeName: "Ang Panunumpa sa mga Ninuno",
        description: "Abraham's unseen stars, Jacob wrestling at the river, and Joseph's long forgiveness.",
        bookRange: "Genesis 12 – 50",
        color: "#38bdf8",
        chapters: [
          {
            id: "genesis-abraham",
            slug: "abraham",
            title: "Abraham · The Ascent of Moriah",
            nativeTitle: "Ang Bundok ng Moria at ang Korderong Ipinagkaloob",
            scripture: "Genesis 12:1–3, 15:5, 22:1–19",
            summary: "Counting the stars in Hebron, walking three days in silence toward Moriah, and trusting God with the promise.",
            route: "/experience/genesis/abraham",
            bookId: "genesis",
            bookName: "Genesis",
            order: 8,
            pov: "Witness",
            emotion: "testing, surrender",
            keyWitnesses: ["Abraham", "Isaac"],
            testament: "old",
          },
          {
            id: "genesis-jacob",
            slug: "jacob",
            title: "Jacob · Wrestling at the Jabbok",
            nativeTitle: "Ang Pakikipagbuno sa Dilim ng Ilog",
            scripture: "Genesis 28:10–19, 32:22–32",
            summary: "A fugitive clutching a stranger in the dust until daybreak. A broken hip and a renamed identity: Israel.",
            route: "/experience/genesis/jacob",
            bookId: "genesis",
            bookName: "Genesis",
            order: 9,
            pov: "Witness",
            emotion: "struggle, blessing",
            keyWitnesses: ["Jacob"],
            testament: "old",
          },
          {
            id: "genesis-joseph",
            slug: "joseph",
            title: "Joseph · The Pit and the Grain",
            nativeTitle: "Ang Hukay sa Dothan at ang Bodega ng Ehipto",
            scripture: "Genesis 37, 45:1–15, 50:20",
            summary: "The torn tunic dipped in goat blood, dark years in an Egyptian dungeon, and tears shed over repentant brothers.",
            route: "/experience/genesis/joseph",
            bookId: "genesis",
            bookName: "Genesis",
            order: 10,
            pov: "Witness",
            emotion: "reconciliation, sovereignty",
            keyWitnesses: ["Joseph", "Judah"],
            testament: "old",
          },
        ],
      },
    ],
  },

  // 3. Exodus & Wilderness
  {
    id: "exodus-wilderness",
    name: "Exodus & The Wilderness",
    tagline: "Out of the iron furnace of Egypt, through the divided sea, into covenant at Sinai.",
    timeframe: "c. 1446 – 1406 BC",
    testament: "old",
    badgeColor: "bg-red-950/40 text-red-300 border-red-500/30",
    accentBorder: "border-red-500/40",
    arcs: [
      {
        id: "arc-exodus",
        eraId: "exodus-wilderness",
        name: "Exodus: Deliverance & Covenant",
        nativeName: "Ang Paglabas at ang Ilang",
        description: "Moses at the burning bush, the ten judgments of Egypt, and thunder upon Mount Sinai.",
        bookRange: "Exodus – Deuteronomy",
        color: "#f87171",
        chapters: [
          {
            id: "exodus-moses",
            slug: "moses",
            title: "Moses · The Bush that Does Not Burn",
            nativeTitle: "Ang Mababang Halamang Hindi Nauubos",
            scripture: "Exodus 3:1 – 4:17",
            summary: "Barefoot on holy desert ground. The shepherd with a stutter summoned to confront the empire of Egypt.",
            route: "/experience/exodus/moses",
            bookId: "exodus",
            bookName: "Exodus",
            order: 11,
            pov: "Witness",
            emotion: "hesitation, holiness",
            keyWitnesses: ["Moses"],
            testament: "old",
          },
          {
            id: "exodus-plagues",
            slug: "plagues",
            title: "The Signs · Blood, Frogs & Midnight",
            nativeTitle: "Ang Sampung Salot at ang Hatinggabi sa Ehipto",
            scripture: "Exodus 7:14 – 12:32",
            summary: "Nile turning to coppery blood, darkness swallowing the sun, and lamb's blood painted upon the doorposts.",
            route: "/experience/exodus/plagues",
            bookId: "exodus",
            bookName: "Exodus",
            order: 12,
            pov: "Witness",
            emotion: "dread, deliverance",
            keyWitnesses: ["Moses", "Aaron", "Pharaoh"],
            testament: "old",
          },
          {
            id: "exodus-red-sea",
            slug: "red-sea",
            title: "The Sea Divided · Wall of Water",
            nativeTitle: "Ang Dagat na Nahati sa Harap ng mga Karwahe",
            scripture: "Exodus 14:1 – 15:21",
            summary: "Trapped between the Egyptian vanguard and the salt waves. The east wind blows all night, carving a pathway of dry dust.",
            route: "/experience/exodus/red-sea",
            bookId: "exodus",
            bookName: "Exodus",
            order: 13,
            pov: "Witness",
            emotion: "panic, salvation",
            keyWitnesses: ["Moses", "Miriam"],
            testament: "old",
          },
          {
            id: "exodus-sinai",
            slug: "sinai",
            title: "Mount Sinai · Smoke and the Ten Words",
            nativeTitle: "Ang Usok at Kulog sa Bundok ng Tipan",
            scripture: "Exodus 19 – 20, 24",
            summary: "A mountain trembling under thick cloud, trumpet blasts shaking stone, and the divine law engraved upon slabs.",
            route: "/experience/exodus/sinai",
            bookId: "exodus",
            bookName: "Exodus",
            order: 14,
            pov: "Witness",
            emotion: "terror, covenant",
            keyWitnesses: ["Moses"],
            testament: "old",
          },
          {
            id: "exodus-wilderness",
            slug: "wilderness",
            title: "The Wilderness · Manna & The Rock",
            nativeTitle: "Ang Manna sa Umaga at ang Tubig sa Bato",
            scripture: "Exodus 16, 17:1–7 · Numbers 20",
            summary: "Forty years under sun and cloud. White coriander bread melting on dew, water pouring from cleft flint.",
            route: "/experience/exodus/wilderness",
            bookId: "exodus",
            bookName: "Exodus",
            order: 15,
            pov: "Witness",
            emotion: "weariness, provision",
            keyWitnesses: ["Moses", "Joshua"],
            testament: "old",
          },
        ],
      },
    ],
  },

  // 4. The Kingdom & Prophets
  {
    id: "kingdom-prophets",
    name: "The Kingdom & The Prophets",
    tagline: "Conquest, golden temple, broken kings, and prophets calling down heaven's fire.",
    timeframe: "c. 1400 – 586 BC",
    testament: "old",
    badgeColor: "bg-indigo-950/40 text-indigo-300 border-indigo-500/30",
    accentBorder: "border-indigo-500/40",
    arcs: [
      {
        id: "arc-kingdom",
        eraId: "kingdom-prophets",
        name: "Kingdom: Conquest, Monarchy & Prophecy",
        nativeName: "Ang Kaharian at ang mga Propeta",
        description: "From the walls of Jericho to the high cedar temple of Solomon and Elijah on Carmel.",
        bookRange: "Joshua – 2 Kings, Isaiah",
        color: "#818cf8",
        chapters: [
          {
            id: "kingdom-joshua",
            slug: "joshua-jericho",
            title: "Joshua · The Crumbling Walls of Jericho",
            nativeTitle: "Ang Pagsabog ng Trompeta sa Jericho",
            scripture: "Joshua 6:1–27",
            summary: "Seven days marching in silence. Seven ram horn blasts, a shout, and massive stone ramparts collapsing inward.",
            route: "/experience/kingdom/joshua-jericho",
            bookId: "joshua",
            bookName: "Joshua",
            order: 16,
            pov: "Witness",
            emotion: "triumph, reverence",
            keyWitnesses: ["Joshua", "Rahab"],
            testament: "old",
          },
          {
            id: "kingdom-gideon",
            slug: "gideon",
            title: "Gideon · Three Hundred Torches",
            nativeTitle: "Ang Tatlong Daan sa Dilim",
            scripture: "Judges 6 – 7",
            summary: "Sifting an army at the spring of Harod. Clay jars shattered in the midnight darkness, shouting for the Lord and Gideon.",
            route: "/experience/kingdom/gideon",
            bookId: "judges",
            bookName: "Judges",
            order: 17,
            pov: "Witness",
            emotion: "fear, faith",
            keyWitnesses: ["Gideon"],
            testament: "old",
          },
          {
            id: "kingdom-ruth",
            slug: "ruth",
            title: "Ruth · The Barley Fields of Bethlehem",
            nativeTitle: "Ang Uhay ng Sebada sa Bethlehem",
            scripture: "Ruth 1 – 4",
            summary: "Gleaning behind harvesters in dusty heat. A Moabite widow finding loyalty, covenant, and a kinsman-redeemer.",
            route: "/experience/kingdom/ruth",
            bookId: "ruth",
            bookName: "Ruth",
            order: 18,
            pov: "Witness",
            emotion: "tenderness, redemption",
            keyWitnesses: ["Ruth", "Boaz", "Naomi"],
            testament: "old",
          },
          {
            id: "kingdom-samuel",
            slug: "samuel",
            title: "Samuel · The Voice in the Tabernacle",
            nativeTitle: "Magsalita Kayo, Panginoon",
            scripture: "1 Samuel 3:1–21",
            summary: "The lamp of God not yet extinguished at Shiloh. A young boy answering in the dark: 'Speak, for your servant hears.'",
            route: "/experience/kingdom/samuel",
            bookId: "1-samuel",
            bookName: "1 Samuel",
            order: 19,
            pov: "Witness",
            emotion: "vocation, stillness",
            keyWitnesses: ["Samuel", "Eli"],
            testament: "old",
          },
          {
            id: "kingdom-david-goliath",
            slug: "david-goliath",
            title: "David · Five Smooth Stones in the Valley",
            nativeTitle: "Ang Limang Makinis na Bato sa Elah",
            scripture: "1 Samuel 17",
            summary: "The bronze armor discarded for a shepherd's sling. The giant blaspheming the armies of the living God.",
            route: "/experience/kingdom/david-goliath",
            bookId: "1-samuel",
            bookName: "1 Samuel",
            order: 20,
            pov: "Witness",
            emotion: "courage, zeal",
            keyWitnesses: ["David", "Goliath"],
            testament: "old",
          },
          {
            id: "kingdom-david-fall",
            slug: "david-fall",
            title: "David's Fall · Broken Bones & Repentance",
            nativeTitle: "Ang Pagkabasag ng Makasalanang Hari",
            scripture: "2 Samuel 11 – 12 · Psalm 51",
            summary: "Nathan points his finger: 'You are the man.' A king weeping into the dust, asking for a clean heart.",
            route: "/experience/kingdom/david-fall",
            bookId: "2-samuel",
            bookName: "2 Samuel",
            order: 21,
            pov: "Witness",
            emotion: "conviction, grace",
            keyWitnesses: ["David", "Nathan"],
            testament: "old",
          },
          {
            id: "kingdom-solomon",
            slug: "solomon-temple",
            title: "Solomon · Cloud in the Holy of Holies",
            nativeTitle: "Ang Ulap sa Banal ng mga Banal",
            scripture: "1 Kings 8:1–66",
            summary: "Gold leaf, carved cherubim, and the priests unable to stand because the glory of the Lord fills the temple.",
            route: "/experience/kingdom/solomon-temple",
            bookId: "1-kings",
            bookName: "1 Kings",
            order: 22,
            pov: "Witness",
            emotion: "splendor, majesty",
            keyWitnesses: ["Solomon"],
            testament: "old",
          },
          {
            id: "kingdom-elijah",
            slug: "elijah-carmel",
            title: "Elijah · The Fire on Mount Carmel",
            nativeTitle: "Ang Apoy mula sa Langit",
            scripture: "1 Kings 18:20–46, 19:1–18",
            summary: "Twelve water jugs poured upon the altar. Fire falls, licking up dust and stones. Then a whisper in a cave.",
            route: "/experience/kingdom/elijah-carmel",
            bookId: "1-kings",
            bookName: "1 Kings",
            order: 23,
            pov: "Witness",
            emotion: "confrontation, silence",
            keyWitnesses: ["Elijah"],
            testament: "old",
          },
          {
            id: "kingdom-divided",
            slug: "divided-kingdom",
            title: "The Divided Kingdom · The Torn Robe",
            nativeTitle: "Ang Napunit na Balabal ng Kaharian",
            scripture: "1 Kings 11:29–39, 12:1–24",
            summary: "Rehoboam's arrogance scorpions versus whips. Ten pieces of cloak torn away; northern and southern kingdoms fractured.",
            route: "/experience/kingdom/divided-kingdom",
            bookId: "1-kings",
            bookName: "1 Kings",
            order: 24,
            pov: "Witness",
            emotion: "grief, disintegration",
            testament: "old",
          },
          {
            id: "kingdom-isaiah",
            slug: "isaiah-vision",
            title: "Isaiah · Seraphim & The Burning Coal",
            nativeTitle: "Ang Baga mula sa Dambana",
            scripture: "Isaiah 6:1–13",
            summary: "The year King Uzziah died: the Lord high and lifted up, doorposts shaking, and coal touching trembling lips.",
            route: "/experience/kingdom/isaiah-vision",
            bookId: "isaiah",
            bookName: "Isaiah",
            order: 25,
            pov: "Witness",
            emotion: "holiness, cleansing",
            keyWitnesses: ["Isaiah"],
            testament: "old",
          },
        ],
      },
    ],
  },

  // 5. Exile & Lamentation
  {
    id: "exile-lamentation",
    name: "Exile & Lamentation",
    tagline: "The burning of Zion, weeping by the rivers of Babylon, and faithfulness in exile.",
    timeframe: "c. 586 – 538 BC",
    testament: "old",
    badgeColor: "bg-stone-900/60 text-stone-300 border-stone-600/40",
    accentBorder: "border-stone-500/40",
    arcs: [
      {
        id: "arc-exile",
        eraId: "exile-lamentation",
        name: "Exile: Ashes, Dispersion & Faith",
        nativeName: "Ang Pagkabihag at ang Abo",
        description: "The weepings of Jeremiah, Jerusalem reduced to ash, and Daniel facing lions in Babylon.",
        bookRange: "Jeremiah, Lamentations, Daniel, Esther, Job",
        color: "#a8a29e",
        chapters: [
          {
            id: "exile-jeremiah",
            slug: "jeremiah",
            title: "Jeremiah · The Mire of the Cistern",
            nativeTitle: "Ang Putik ng Balon at ang Apoy sa Buto",
            scripture: "Jeremiah 20:7–9, 38:1–13",
            summary: "Sinking into mud up to the chest. A prophet crying out against false peace while fire burns inside his bones.",
            route: "/experience/exile/jeremiah",
            bookId: "jeremiah",
            bookName: "Jeremiah",
            order: 26,
            pov: "Witness",
            emotion: "loneliness, persistence",
            keyWitnesses: ["Jeremiah"],
            testament: "old",
          },
          {
            id: "exile-fall-of-jerusalem",
            slug: "fall-of-jerusalem",
            title: "Fall of Jerusalem · The Silence of Ash",
            nativeTitle: "Ang Pagbagsak ng Jerusalem at Katahimikan ng Abo",
            scripture: "2 Kings 25 · Lamentations 1 – 3",
            summary: "Solomon's temple torched to the bedrock. Zion sitting solitary like a widow, weeping in the night.",
            route: "/experience/exile/fall-of-jerusalem",
            bookId: "lamentations",
            bookName: "Lamentations",
            order: 27,
            pov: "Theo / Immersive Witness",
            emotion: "devastation, lament",
            keyWitnesses: ["Jeremiah"],
            testament: "old",
          },
          {
            id: "exile-daniel",
            slug: "daniel",
            title: "Daniel · The Window Toward Zion",
            nativeTitle: "Ang Bintana Patungong Sion sa Gitna ng Babilonia",
            scripture: "Daniel 3:1–30, 6:1–28",
            summary: "Three men walking unburnt inside the furnace with a fourth figure like the Son of God. The silent den of lions.",
            route: "/experience/exile/daniel",
            bookId: "daniel",
            bookName: "Daniel",
            order: 28,
            pov: "Witness",
            emotion: "resolve, steadfastness",
            keyWitnesses: ["Daniel", "Shadrach", "Meshach", "Abednego"],
            testament: "old",
          },
          {
            id: "exile-esther",
            slug: "esther",
            title: "Esther · For Such a Time as This",
            nativeTitle: "Ang Gintong Setro sa Palasyo ng Susa",
            scripture: "Esther 4 – 7",
            summary: "Fast three days; then walk before the Persian king unbidden: 'If I perish, I perish.' The golden scepter extended.",
            route: "/experience/exile/esther",
            bookId: "esther",
            bookName: "Esther",
            order: 29,
            pov: "Witness",
            emotion: "peril, courage",
            keyWitnesses: ["Esther", "Mordecai"],
            testament: "old",
          },
          {
            id: "exile-job",
            slug: "job",
            title: "Job · Voice from the Whirlwind",
            nativeTitle: "Ang Abo at ang Tinig Mula sa Buhawi",
            scripture: "Job 1 – 2, 38 – 42",
            summary: "Sitting in ashes scraping sores with pottery. God questions him: 'Where were you when I laid the earth's foundations?'",
            route: "/experience/exile/job",
            bookId: "job",
            bookName: "Job",
            order: 30,
            pov: "Witness",
            emotion: "agony, mystery",
            keyWitnesses: ["Job"],
            testament: "old",
          },
        ],
      },
    ],
  },

  // 6. Restoration & The Silent Years
  {
    id: "restoration-silent",
    name: "Restoration & The Silent Years",
    tagline: "The return from Persian dust, the rebuilding of rubble, and four centuries of silence.",
    timeframe: "c. 538 – 4 BC",
    testament: "old",
    badgeColor: "bg-teal-950/40 text-teal-300 border-teal-500/30",
    accentBorder: "border-teal-500/40",
    arcs: [
      {
        id: "arc-restoration",
        eraId: "restoration-silent",
        name: "Restoration: Rebuilding & Silence",
        nativeName: "Ang Muling Pagsikat at ang Katahimikan",
        description: "From Cyrus's decree to the sword-and-trowel builders of Jerusalem, ending in waiting.",
        bookRange: "Ezra, Nehemiah, Malachi",
        color: "#2dd4bf",
        chapters: [
          {
            id: "restoration-return",
            slug: "return",
            title: "The Return · Foundations Laid with Tears",
            nativeTitle: "Ang Muling Pagsikat sa Guho",
            scripture: "Ezra 1 – 3",
            summary: "Elderly priests who saw Solomon's temple weep aloud while the young shout for joy over modest foundation stones.",
            route: "/experience/restoration/return",
            bookId: "ezra",
            bookName: "Ezra",
            order: 31,
            pov: "Witness",
            emotion: "hope, mixed grief",
            keyWitnesses: ["Zerubbabel", "Jeshua"],
            testament: "old",
          },
          {
            id: "restoration-ezra-nehemiah",
            slug: "ezra-nehemiah",
            title: "Ezra & Nehemiah · Sword and Trowel",
            nativeTitle: "Ang Pader at ang Templo sa Ulan",
            scripture: "Nehemiah 4, 8:1–12",
            summary: "Guarding half-built broken masonry with spears. Ezra unrolls the scroll; the congregation weeps in the autumn rain.",
            route: "/experience/restoration/ezra-nehemiah",
            bookId: "nehemiah",
            bookName: "Nehemiah",
            order: 32,
            pov: "Witness",
            emotion: "vigilance, renewal",
            keyWitnesses: ["Ezra", "Nehemiah"],
            testament: "old",
          },
          {
            id: "restoration-silent-years",
            slug: "silent-years",
            title: "The Silent Years · Four Hundred Winters",
            nativeTitle: "Ang Apatnaraang Taon ng Paghihintay",
            scripture: "Malachi 4:5–6 · Luke 1:5–25",
            summary: "No prophet's voice in Judea. Roman iron shields marching across cobblestone, until an angel enters Zechariah's sanctuary.",
            route: "/experience/restoration/silent-years",
            bookId: "malachi",
            bookName: "Malachi",
            order: 33,
            pov: "Witness",
            emotion: "yearning, threshold",
            testament: "old",
          },
        ],
      },
    ],
  },

  // 7. The Gospels
  {
    id: "gospels-incarnation",
    name: "The Incarnation & Ministry",
    tagline: "The Word made flesh: walking on dust, healing broken bodies, and confronting power.",
    timeframe: "c. 4 BC – AD 30",
    testament: "new",
    badgeColor: "bg-blue-950/40 text-blue-300 border-blue-500/30",
    accentBorder: "border-blue-500/40",
    arcs: [
      {
        id: "arc-gospels",
        eraId: "gospels-incarnation",
        name: "The Gospels: Jesus of Nazareth",
        nativeName: "Ang Salitang Nagkatawang-Tao",
        description: "The public ministry, wonders, parables, and Theo's pivotal encounter with Christ.",
        bookRange: "Matthew, Mark, Luke, John",
        color: "#60a5fa",
        chapters: [
          {
            id: "gospel-first-sight",
            slug: "first-sight",
            title: "First Sight · The Voice at the Jordan",
            nativeTitle: "Ang Tinig sa Ilang at ang Kordero",
            scripture: "Matthew 3, John 1:29–34",
            summary: "John baptizing in muddy currents. A carpenter steps into the river, heaven opens like torn linen, and a dove descends.",
            route: "/experience/gospels/first-sight",
            bookId: "matthew",
            bookName: "Matthew",
            order: 34,
            pov: "Theo / First Sight",
            emotion: "revelation, clarity",
            keyWitnesses: ["Jesus", "John the Baptist"],
            testament: "new",
          },
          {
            id: "gospel-crowds",
            slug: "crowds-healing",
            title: "The Crowds · Touching the Hem",
            nativeTitle: "Ang Hipag ng Laylayan sa Gitna ng Tao",
            scripture: "Mark 1, 5:25–34",
            summary: "Crowds pressing close in Capernaum. A woman suffering twelve years touches the fringe of his garment; power goes out.",
            route: "/experience/gospels/crowds-healing",
            bookId: "mark",
            bookName: "Mark",
            order: 35,
            pov: "Witness",
            emotion: "compassion, healing",
            keyWitnesses: ["Jesus"],
            testament: "new",
          },
          {
            id: "gospel-sermon",
            slug: "sermon-mount",
            title: "Sermon on the Mount · Blessed are the Poor",
            nativeTitle: "Mapapalad ang mga Aba sa Espiritu",
            scripture: "Matthew 5 – 7",
            summary: "Sitting on green grass overlooking the sea. Overturning human hierarchies: 'Love your enemies and pray for those who persecute you.'",
            route: "/experience/gospels/sermon-mount",
            bookId: "matthew",
            bookName: "Matthew",
            order: 36,
            pov: "Witness",
            emotion: "authority, revolution",
            keyWitnesses: ["Jesus", "Disciples"],
            testament: "new",
          },
          {
            id: "gospel-storm",
            slug: "storm-calmed",
            title: "The Gale on Galilee · Peace, Be Still",
            nativeTitle: "Pumayapa Ka: Ang Bagyo sa Dagat",
            scripture: "Mark 4:35–41",
            summary: "Water filling the wooden gunwales. Sleeping on a cushion in the stern, Jesus wakes: 'Quiet! Be still!' The wind ceases instantly.",
            route: "/experience/gospels/storm-calmed",
            bookId: "mark",
            bookName: "Mark",
            order: 37,
            pov: "Witness",
            emotion: "terror, awe",
            keyWitnesses: ["Jesus", "Peter"],
            testament: "new",
          },
          {
            id: "gospel-confession",
            slug: "caesarea-philippi",
            title: "Caesarea Philippi · You Are the Christ",
            nativeTitle: "Ikaw ang Cristo, ang Anak ng Diyos na Buhay",
            scripture: "Matthew 16:13–28",
            summary: "At the foot of Mount Hermon near the pagan grottoes: 'Who do you say that I am?' Peter answers with bedrock conviction.",
            route: "/experience/gospels/caesarea-philippi",
            bookId: "matthew",
            bookName: "Matthew",
            order: 38,
            pov: "Witness",
            emotion: "confession, cost",
            keyWitnesses: ["Jesus", "Peter"],
            testament: "new",
          },
          {
            id: "gospel-lazarus",
            slug: "lazarus",
            title: "Bethany · Lazarus, Come Forth",
            nativeTitle: "Lumabas Ka: Ang Luha at ang Libingan",
            scripture: "John 11:1–44",
            summary: "Four days dead behind cold limestone. Jesus weeps, commands the stone removed, and cries with a loud voice into the dark.",
            route: "/experience/gospels/lazarus",
            bookId: "john",
            bookName: "John",
            order: 39,
            pov: "Witness",
            emotion: "grief, resurrection power",
            keyWitnesses: ["Jesus", "Mary", "Martha", "Lazarus"],
            testament: "new",
          },
          {
            id: "gospel-entry",
            slug: "entry-jerusalem",
            title: "Triumphal Entry · Palms and Colt",
            nativeTitle: "Hosanna sa Anak ni David",
            scripture: "Matthew 21:1–11 · Luke 19:28–44",
            summary: "Riding an unbroken donkey foal into shouting gates. Palms laid in dust; Jesus weeps over Jerusalem's coming judgment.",
            route: "/experience/gospels/entry-jerusalem",
            bookId: "matthew",
            bookName: "Matthew",
            order: 40,
            pov: "Witness",
            emotion: "celebration, foreboding",
            keyWitnesses: ["Jesus"],
            testament: "new",
          },
          {
            id: "gospel-supper",
            slug: "last-supper",
            title: "The Upper Room · Towel & Cup",
            nativeTitle: "Ang Tinapay, ang Cawa, at ang Paghuhugas ng Paa",
            scripture: "John 13 – 14 · Luke 22:7–38",
            summary: "Water poured into a basin. The Lord kneeling before calloused, dusty feet. Bread broken: 'This is my body, given for you.'",
            route: "/experience/gospels/last-supper",
            bookId: "john",
            bookName: "John",
            order: 41,
            pov: "Witness",
            emotion: "humility, sacrament",
            keyWitnesses: ["Jesus", "Peter", "John", "Judas"],
            testament: "new",
          },
          {
            id: "gospel-intervention",
            slug: "theos-intervention",
            title: "Theo's Intervention Attempt",
            nativeTitle: "Ang Pagtatangkang Pigilan ang Takdang Oras",
            scripture: "Matthew 26:36–46 · John 18:11",
            summary: "Theo attempts to change the historical outcome and save Jesus. The collapse of his belief that knowledge equals control.",
            route: "/experience/gospels/theos-intervention",
            bookId: "matthew",
            bookName: "Matthew",
            order: 42,
            pov: "Theo / Pivot Point",
            emotion: "helplessness, surrender",
            keyWitnesses: ["Jesus", "Theo"],
            testament: "new",
          },
          {
            id: "gospel-empty-tomb",
            slug: "empty-tomb",
            title: "The Empty Tomb · Dawn on the First Day",
            nativeTitle: "Bakit Ninyo Hinahanap ang Buhay sa mga Patay?",
            scripture: "Luke 24:1–12 · John 20:1–18",
            summary: "The heavy stone rolled aside in the early dew. Folded linen facecloth, dazzling angels, and Mary hearing her name called.",
            route: "/experience/gospels/empty-tomb",
            bookId: "john",
            bookName: "John",
            order: 43,
            pov: "Witness",
            emotion: "wonder, victory",
            keyWitnesses: ["Mary Magdalene", "Peter", "John"],
            testament: "new",
          },
        ],
      },
    ],
  },

  // 8. The Passion & The Cross
  {
    id: "passion-cross",
    name: "The Passion & The Cross",
    tagline: "The cup in Gethsemane, betrayal by kiss, Roman scourging, and total silence at noon.",
    timeframe: "Passover, AD 30",
    testament: "new",
    badgeColor: "bg-rose-950/40 text-rose-300 border-rose-500/30",
    accentBorder: "border-rose-500/40",
    arcs: [
      {
        id: "arc-passion",
        eraId: "passion-cross",
        name: "The Passion: The Darkest Hour",
        nativeName: "Ang Pasyon at ang Krus",
        description: "The agony in the olive grove to Golgotha's hill where sound empties into total silence.",
        bookRange: "Matthew, Mark, Luke, John",
        color: "#fb7185",
        chapters: [
          {
            id: "cross-gethsemane",
            slug: "gethsemane",
            title: "Gethsemane · Sweat Like Great Drops of Blood",
            nativeTitle: "Ang Panalangin sa Ilalim ng mga Olibo",
            scripture: "Luke 22:39–46",
            summary: "Under ancient gnarled olive boughs while disciples sleep: 'Not my will, but yours be done.'",
            route: "/experience/cross/gethsemane",
            bookId: "luke",
            bookName: "Luke",
            order: 44,
            pov: "Theo / Intimate Witness",
            emotion: "agony, obedience",
            keyWitnesses: ["Jesus", "Peter", "James", "John"],
            testament: "new",
          },
          {
            id: "cross-arrest",
            slug: "arrest",
            title: "The Arrest · Torches and Lanterns",
            nativeTitle: "Ang Halik sa Karimlan",
            scripture: "John 18:1–12 · Matthew 26:47–56",
            summary: "Glittering Roman gladii and olive torches. Judas steps forward with a greeting kiss: 'Put your sword back in its place.'",
            route: "/experience/cross/arrest",
            bookId: "john",
            bookName: "John",
            order: 45,
            pov: "Witness",
            emotion: "betrayal, composure",
            keyWitnesses: ["Jesus", "Judas", "Peter"],
            testament: "new",
          },
          {
            id: "cross-denial",
            slug: "peter-denial",
            title: "Peter's Denial · Charcoal Fire & Rooster",
            nativeTitle: "Ang Pagtilaok ng Manok sa Hukuman",
            scripture: "Luke 22:54–62",
            summary: "Warming hands in the high priest's courtyard. Three times denying knowing him, until the rooster crows and eyes lock across the courtyard.",
            route: "/experience/cross/peter-denial",
            bookId: "luke",
            bookName: "Luke",
            order: 46,
            pov: "Witness",
            emotion: "failure, weeping",
            keyWitnesses: ["Peter", "Jesus"],
            testament: "new",
          },
          {
            id: "cross-trial",
            slug: "the-trial",
            title: "The Trial · What is Truth?",
            nativeTitle: "Ano ang Katotohanan sa Harap ni Pilato?",
            scripture: "John 18:28 – 19:16",
            summary: "A bruised prophet in purple rags standing before Roman imperial power. Pilate washes his hands over a bronze basin.",
            route: "/experience/cross/the-trial",
            bookId: "john",
            bookName: "John",
            order: 47,
            pov: "Witness",
            emotion: "injustice, majesty",
            keyWitnesses: ["Jesus", "Pilate"],
            testament: "new",
          },
          {
            id: "cross-crucifixion",
            slug: "crucifixion",
            title: "The Crucifixion · Darkness at Midday",
            nativeTitle: "Ang Dilim sa Katanghaliang Tapat",
            scripture: "Mark 15:21–41 · Luke 23:32–49 · John 19:17–37",
            summary: "Iron driven through wrists on the skull hill. Noon turning to black twilight, the temple veil torn, and a quiet breath: 'It is finished.'",
            route: "/experience/cross/crucifixion",
            bookId: "john",
            bookName: "John",
            order: 48,
            pov: "Theo / Absolute Restraint",
            emotion: "stillness, salvation",
            keyWitnesses: ["Jesus", "Mary", "John", "Centurion"],
            testament: "new",
          },
        ],
      },
    ],
  },

  // 9. The Apostolic Church (Acts)
  {
    id: "acts-apostolic",
    name: "The Early Church & Apostles",
    tagline: "Tongues of fire, bread broken from house to house, Stephen's witness, and Saul transformed.",
    timeframe: "c. AD 30 – 62",
    testament: "new",
    badgeColor: "bg-purple-950/40 text-purple-300 border-purple-500/30",
    accentBorder: "border-purple-500/40",
    arcs: [
      {
        id: "arc-acts",
        eraId: "acts-apostolic",
        name: "Acts: The Movement of the Spirit",
        nativeName: "Ang Pagkilos ng Espiritu Santo",
        description: "From Pentecost's rushing wind to the spread of the gospel across Antioch, Greece, and Rome.",
        bookRange: "Acts of the Apostles",
        color: "#c084fc",
        chapters: [
          {
            id: "acts-pentecost",
            slug: "pentecost",
            title: "Pentecost · A Sound Like a Rushing Wind",
            nativeTitle: "Ang Hanging Umaugong at Dila ng Apoy",
            scripture: "Acts 2:1–41",
            summary: "The upper room filled with a sound like violent wind. Divided flames rest on each disciple; foreign dialects spoken with clarity.",
            route: "/experience/acts/pentecost",
            bookId: "acts",
            bookName: "Acts",
            order: 49,
            pov: "Witness",
            emotion: "fervor, birth",
            keyWitnesses: ["Peter", "Apostles"],
            testament: "new",
          },
          {
            id: "acts-early-church",
            slug: "early-church",
            title: "The Fellowship · One Heart and Soul",
            nativeTitle: "Ang Pagpuputul-putol ng Tinapay",
            scripture: "Acts 2:42–47, 4:32–37",
            summary: "No one claiming possessions as their own. Breaking bread from house to house with glad and sincere hearts.",
            route: "/experience/acts/early-church",
            bookId: "acts",
            bookName: "Acts",
            order: 50,
            pov: "Witness",
            emotion: "unity, generosity",
            keyWitnesses: ["Barnabas", "Peter"],
            testament: "new",
          },
          {
            id: "acts-stephen",
            slug: "stephen",
            title: "Stephen · The Face of an Angel",
            nativeTitle: "Ang Mukha ng Isang Anghel at ang Langit",
            scripture: "Acts 6:8 – 7:60",
            summary: "Stoned outside the Damascus gate under flying boulders: 'Lord, do not hold this sin against them.' Looking up to see Jesus standing at God's right hand.",
            route: "/experience/acts/stephen",
            bookId: "acts",
            bookName: "Acts",
            order: 51,
            pov: "Witness",
            emotion: "peace, sacrifice",
            keyWitnesses: ["Stephen", "Saul"],
            testament: "new",
          },
          {
            id: "acts-paul",
            slug: "paul",
            title: "Saul on the Damascus Road · The Light",
            nativeTitle: "Saulo, Saulo, Bakit Mo Ako Pinag-uusig?",
            scripture: "Acts 9:1–31",
            summary: "Blinded by noon radiance brighter than the sun. The persecutor led by the hand into Damascus to become an apostle of grace.",
            route: "/experience/acts/paul",
            bookId: "acts",
            bookName: "Acts",
            order: 52,
            pov: "Witness",
            emotion: "transformation, calling",
            keyWitnesses: ["Paul", "Ananias"],
            testament: "new",
          },
        ],
      },
    ],
  },

  // 10. The Apocalypse & The New Creation
  {
    id: "apocalypse-revelation",
    name: "The Apocalypse & Eschaton",
    tagline: "The unsealed scroll on Patmos, the Lamb upon the throne, and the city with no temple.",
    timeframe: "The End of the Age / Eternity",
    testament: "new",
    badgeColor: "bg-fuchsia-950/40 text-fuchsia-300 border-fuchsia-500/30",
    accentBorder: "border-fuchsia-500/40",
    arcs: [
      {
        id: "arc-revelation",
        eraId: "apocalypse-revelation",
        name: "Revelation: The Unveiling",
        nativeName: "Ang Pagbubunyag at ang Bagong Jerusalem",
        description: "John on Patmos, the Lamb unsealing history, and the river of the water of life.",
        bookRange: "Revelation 1 – 22",
        color: "#e879f9",
        chapters: [
          {
            id: "revelation-begins",
            slug: "begins",
            title: "Patmos · The Voice Behind Like a Trumpet",
            nativeTitle: "Ang Tinig sa Likod ng Islang Bato",
            scripture: "Revelation 1:9–20",
            summary: "Exiled on salt volcanic cliffs on the Lord's Day. Turning to see seven golden lampstands and the Son of Man with eyes like fire.",
            route: "/experience/revelation/begins",
            bookId: "revelation",
            bookName: "Revelation",
            order: 53,
            pov: "Witness",
            emotion: "awe, commission",
            keyWitnesses: ["John"],
            testament: "new",
          },
          {
            id: "revelation-throne",
            slug: "throne-scroll",
            title: "The Throne Room · The Slain Lamb",
            nativeTitle: "Ang Korderong Mukhang Pinatay",
            scripture: "Revelation 4 – 5",
            summary: "A rainbow around the jasper throne, four living creatures chanting without ceasing, and the Lion of Judah who is a standing Lamb.",
            route: "/experience/revelation/throne-scroll",
            bookId: "revelation",
            bookName: "Revelation",
            order: 54,
            pov: "Witness",
            emotion: "adoration, sovereignty",
            keyWitnesses: ["John", "The Lamb"],
            testament: "new",
          },
          {
            id: "revelation-theo-understands",
            slug: "theo-understands",
            title: "Theo Understands · The Surrender of Control",
            nativeTitle: "Ang Pagkaunawa at Pagsuko ni Theo",
            scripture: "Revelation 19:6–16 · Matthew 6:34",
            summary: "Theo recognizes that history is not a machinery to be fixed by human anxiety, but a covenant carried by the Lamb.",
            route: "/experience/revelation/theo-understands",
            bookId: "revelation",
            bookName: "Revelation",
            order: 55,
            pov: "Theo / Resolution",
            emotion: "peace, acceptance",
            testament: "new",
          },
          {
            id: "revelation-final-vision",
            slug: "final-vision",
            title: "The New Jerusalem · Water of Life",
            nativeTitle: "Ang Bagong Jerusalem at ang Tubig ng Buhay",
            scripture: "Revelation 21 – 22",
            summary: "No temple in the city, for God and the Lamb are its temple. The leaves of the tree are for the healing of the nations.",
            route: "/experience/revelation/final-vision",
            bookId: "revelation",
            bookName: "Revelation",
            order: 56,
            pov: "Theo & John",
            emotion: "restoration, eternity",
            testament: "new",
          },
        ],
      },
    ],
  },

  // 11. The Awakening
  {
    id: "awakening-culmination",
    name: "The Awakening on the Mountain",
    tagline: "Dawn breaking on the limestone ridge — stepping down into the valley transformed.",
    timeframe: "Present Dawn",
    testament: "narrative",
    badgeColor: "bg-amber-900/40 text-amber-200 border-amber-500/30",
    accentBorder: "border-amber-400/40",
    arcs: [
      {
        id: "arc-awakening",
        eraId: "awakening-culmination",
        name: "Epilogue: Returning Home",
        nativeName: "Ang Pagbaba sa Lambak",
        description: "Theo wakes with dew on his jacket, packs his Bible, and sends a single honest message to Sam.",
        bookRange: "Culmination Sequence",
        color: "#fbbf24",
        chapters: [
          {
            id: "awakening-full",
            slug: "full",
            title: "The Full Wake-Up · Dew & Limestone",
            nativeTitle: "Ang Pagdilat sa Liwayway ng Bundok",
            scripture: "Romans 8:18–28 · Philippians 4:6–7",
            summary: "The complete 11-stage wake-up sequence on the mountain ridge. Theo embraces his ordinary life without the false compulsion to control it.",
            route: "/experience/awakening/full",
            order: 57,
            pov: "Theo",
            emotion: "transformed, peace, hope",
            testament: "epilogue",
          },
        ],
      },
    ],
  },
];

// Helper to get total counts
export const ALL_CHRONICLE_CHAPTERS: ChronicleChapter[] = CANON_ERAS.flatMap((era) =>
  era.arcs.flatMap((arc) => arc.chapters)
);

export const CHAPTER_COUNT = ALL_CHRONICLE_CHAPTERS.length;
export const ERA_COUNT = CANON_ERAS.length;
export const ARC_COUNT = CANON_ERAS.reduce((acc, era) => acc + era.arcs.length, 0);
